### ISSUE TITLE
10/20 3:40pm pull request for Monday's report

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/ccc_biospecimen_metrics_gcp_pipeline#13]
There was a typo in the table's new row that is now fixed. If you please test this in GCP to make sure it runs, I'll delete the one we ran just a few minutes ago.

Thank you!

**Comment by jacobmpeters** [comment]
I'm testing it now...

**Comment by jacobmpeters** [comment]
The report ran successfully and is set to run Monday at 11:30 AM. You might want to delete the file that was just created from the Box folder.
